# Generated by Django 6.0 on 2025-12-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_telegram_chat_id_user_telegram_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_token",
        ),
    ]
